# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'arm_conn'
    subscriptionId: '72f19523-2ed0-4bde-abb7-eb01f5ac6197'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm_rg'
    location: 'France Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/elo-nexworld/arm_deployment/main/WebSite.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/elo-nexworld/arm_deployment/main/WebSite.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

